# Generated by Django 2.0 on 2017-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Definition_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_ids', models.CharField(max_length=58)),
                ('name_short', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
