# Generated by Django 2.0 on 2017-12-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openassets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_ids', models.CharField(max_length=58)),
                ('asset_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('colored', models.BooleanField(default=True)),
                ('marker_output', models.BinaryField(max_length=48)),
            ],
        ),
    ]
