# Generated by Django 2.0 on 2017-12-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openassets', '0002_outputs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outputs',
            new_name='Output',
        ),
    ]
